openapi: 3.0.0
info:
  title: example-knowledgebase
  version: 2.0.0
  description: API Documentation
  contact:
    name: example Support
    email: support@example.com
    url: 'https://www.example.com/about-example/contact-us/'
tags:
  - name: knowledge-base
servers:
  - url: 'https://api.example.com'
    description: Partner - All Others
  - url: 'https://{subdomain}.api.example.com'
    description: Partner or Client custom branded sub-domain
    variables:
      subdomain:
        default: demo
        description: Custom sub-domain assigned to the client
paths:
  '/api/v2/tenants/{tenantId}/kb/{articleId}/activitylog':
    get:
      summary: Get article activity log
      description: >
        This endpoint is used to get activity log with provided details of an
        article.


        ## Sample URLs

        ```

        https://{api-url}/api/v2/tenants/client_11/kb/article/KB0000000036/activityLog?pageNo=1&pageSize=20

        ```
      operationId: knowledge-base-article-activity-log-get/
      tags:
        - knowledge-base
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        operation:
                          type: string
                        message:
                          type: string
                        updateTIme:
                          type: string
                          format: date-time
                        updatedBy:
                          title: user
                          type: object
                          properties:
                            id:
                              type: string
                            loginName:
                              type: string
                            lastName:
                              type: string
                            firstName:
                              type: string
                            email:
                              type: string
                            phoneNumber:
                              type: string
                            mobileNumber:
                              type: string
                  totalResults:
                    type: integer
                  orderBy:
                    type: string
                  pageNo:
                    type: integer
                  pageSize:
                    type: integer
                  totalPages:
                    type: integer
                  nextPage:
                    type: boolean
                  previousPageNo:
                    type: integer
                  descendingOrder:
                    type: boolean
              examples:
                example-1:
                  value:
                    results:
                      - operation: UPDATE
                        message: >-
                          Updated <b>content</b>Updated <b>subject</b> of
                          article
                        updateTIme: '2019-05-10T06:01:24+0000'
                        updatedBy:
                          id: USR0000000002
                          loginName: example_api_user
                          lastName: ' '
                          firstName: example API User
                          email: dev@example.com
                      - operation: ATTACH
                        message: >-
                          <div><strong>Attached file(s) to
                          article:</strong><div><i class='icon-file'></i>
                          2.txt</div><div><i class='icon-file'></i>
                          1.txt</div><div><i class='icon-file'></i>
                          bustkt.pdf</div><div><i class='icon-file'></i>
                          bustkt.pdf</div><div><i class='icon-file'></i>
                          queries.txt</div></div>
                        updateTIme: '2019-05-10T06:01:24+0000'
                        updatedBy:
                          id: USR0000000002
                          loginName: example_api_user
                          lastName: ' '
                          firstName: example API User
                          email: dev@example.com
                      - operation: ATTACH
                        message: >-
                          <div><strong>Attached file(s) to
                          article:</strong><div><i class='icon-file'></i>
                          2.txt</div><div><i class='icon-file'></i>
                          1.txt</div><div><i class='icon-file'></i>
                          bustkt.pdf</div><div><i class='icon-file'></i>
                          bustkt.pdf</div></div>
                        updateTIme: '2019-05-10T05:53:36+0000'
                        updatedBy:
                          id: USR0000000003
                          loginName: superadmin
                          lastName: Admin
                          firstName: example
                          email: dev@example.com
                          phoneNumber: ''
                      - operation: ATTACH
                        message: >-
                          <div><strong>Attached file(s) to
                          article:</strong><div><i class='icon-file'></i>
                          2.txt</div><div><i class='icon-file'></i>
                          1.txt</div><div><i class='icon-file'></i>
                          bustkt.pdf</div></div>
                        updateTIme: '2019-05-10T05:53:17+0000'
                        updatedBy:
                          id: USR0000000003
                          loginName: superadmin
                          lastName: Admin
                          firstName: example
                          email: dev@example.com
                          phoneNumber: ''
                      - operation: ATTACH
                        message: >-
                          <div><strong>Attached file(s) to
                          article:</strong><div><i class='icon-file'></i>
                          2.txt</div><div><i class='icon-file'></i>
                          1.txt</div></div><div><strong>Removed
                          file(s):</strong><div><i class='icon-file'></i>
                          3.txt</div><div><i class='icon-file'></i>
                          3.txt</div><div><i class='icon-file'></i>
                          3.txt</div></div>
                        updateTIme: '2019-05-10T05:53:02+0000'
                        updatedBy:
                          id: USR0000000003
                          loginName: superadmin
                          lastName: Admin
                          firstName: example
                          email: dev@example.com
                          phoneNumber: ''
                      - operation: ATTACH
                        message: >-
                          <div><strong>Attached file(s) to
                          article:</strong><div><i class='icon-file'></i>
                          2.txt</div><div><i class='icon-file'></i>
                          1.txt</div><div><i class='icon-file'></i>
                          3.txt</div><div><i class='icon-file'></i>
                          3.txt</div><div><i class='icon-file'></i>
                          3.txt</div></div>
                        updateTIme: '2019-05-10T05:52:27+0000'
                        updatedBy:
                          id: USR0000000002
                          loginName: example_api_user
                          lastName: ' '
                          firstName: example API User
                          email: dev@example.com
                      - operation: UPDATE
                        message: Updated <b>expiryDate</b> of article
                        updateTIme: '2019-05-10T05:52:00+0000'
                        updatedBy:
                          id: USR0000000003
                          loginName: superadmin
                          lastName: Admin
                          firstName: example
                          email: dev@example.com
                          phoneNumber: ''
                      - operation: ATTACH
                        message: >-
                          <div><strong>Attached file(s) to
                          article:</strong><div><i class='icon-file'></i>
                          2.txt</div><div><i class='icon-file'></i>
                          1.txt</div><div><i class='icon-file'></i>
                          3.txt</div><div><i class='icon-file'></i>
                          3.txt</div></div>
                        updateTIme: '2019-05-10T05:51:08+0000'
                        updatedBy:
                          id: USR0000000002
                          loginName: example_api_user
                          lastName: ' '
                          firstName: example API User
                          email: dev@example.com
                      - operation: ATTACH
                        message: >-
                          <div><strong>Attached file(s) to
                          article:</strong><div><i class='icon-file'></i>
                          2.txt</div><div><i class='icon-file'></i>
                          1.txt</div><div><i class='icon-file'></i>
                          3.txt</div></div>
                        updateTIme: '2019-05-10T05:41:38+0000'
                        updatedBy:
                          id: USR0000000002
                          loginName: example_api_user
                          lastName: ' '
                          firstName: example API User
                          email: dev@example.com
                      - operation: UPDATE
                        message: Updated <b>content</b> of article
                        updateTIme: '2019-05-08T12:19:45+0000'
                        updatedBy:
                          id: USR0000000002
                          loginName: example_api_user
                          lastName: ' '
                          firstName: example API User
                          email: dev@example.com
                      - operation: COMMENT
                        message: >-
                          Commented on the article and comment is <b><div
                          class='ActivityLogDetails '> <p class='AttributeName '
                          > Queries Please</p> </div></b>
                        updateTIme: '2019-05-08T12:05:58+0000'
                        updatedBy:
                          id: USR0000000009
                          loginName: Client_User
                          lastName: User
                          firstName: Client
                          email: dev@example.com
                          phoneNumber: ''
                      - operation: UPDATE
                        message: >-
                          Updated <b>content</b>Updated <b>subject</b>Updated
                          <b>expiryDate</b> of article
                        updateTIme: '2019-05-08T12:03:01+0000'
                        updatedBy:
                          id: USR0000000002
                          loginName: example_api_user
                          lastName: ' '
                          firstName: example API User
                          email: dev@example.com
                      - operation: UPDATE
                        message: Updated <b>expiryDate</b> of article
                        updateTIme: '2019-05-08T11:23:20+0000'
                        updatedBy:
                          id: USR0000000009
                          loginName: Client_User
                          lastName: User
                          firstName: Client
                          email: dev@example.com
                          phoneNumber: ''
                      - operation: UPDATE
                        message: >-
                          Added <b>Related Articles</b><br />Related articles
                          are <br /><div class='ActivityLogDetails '><p
                          class='AttributeName' ><b>All Data</div>
                        updateTIme: '2019-05-08T11:23:20+0000'
                        updatedBy:
                          id: USR0000000009
                          loginName: Client_User
                          lastName: User
                          firstName: Client
                          email: dev@example.com
                          phoneNumber: ''
                      - operation: UPDATE
                        message: |-
                          Added <b>uniqueId</b>
                            of article
                        updateTIme: '2019-05-08T10:55:37+0000'
                        updatedBy:
                          id: USR0000000002
                          loginName: example_api_user
                          lastName: ' '
                          firstName: example API User
                          email: dev@example.com
                      - operation: CREATE
                        message: Created the Article in category <b>Cassandra</b>.
                        updateTIme: '2019-05-08T10:55:27+0000'
                        updatedBy:
                          id: USR0000000002
                          loginName: example_api_user
                          lastName: ' '
                          firstName: example API User
                          email: dev@example.com
                    totalResults: 16
                    orderBy: ''
                    pageNo: 1
                    pageSize: 20
                    totalPages: 1
                    nextPage: false
                    previousPageNo: 0
                    descendingOrder: true
      externalDocs:
        url: >-
          https://docs.example.com/api/knowledge-base/knowledge-base-article-activity-log-get/
      parameters:
        - schema:
            type: string
          in: path
          name: tenantId
          required: true
        - schema:
            type: string
          in: path
          name: articleId
          required: true